name: CarRent
description: "hoops app to rent cars"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ferari.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ferari.jpg
    - assets/images/lambo.jpg
    - assets/images/honda.png